import { NextResponse } from "next/server";
import { GoogleGenerativeAI } from "@google/generative-ai";

export async function POST(req: Request) {
  try {
    const body = await req.json().catch(() => ({}));
    const message = body.message || "";
    
    // Capture history from whatever key the frontend is using, fallback to empty array
    const rawHistory = body.conversationHistory || body.history || body.messages || [];
    const history = Array.isArray(rawHistory) ? rawHistory : [];

    // 1. API Key Rotation Setup
    const apiKeysString = process.env.GEMINI_API_KEYS || process.env.GEMINI_API_KEY || "";
    const apiKeys = apiKeysString.split(',').map(key => key.trim()).filter(Boolean);

    if (apiKeys.length === 0) {
      return NextResponse.json({ error: "No Gemini API keys configured." }, { status: 500 });
    }
    const randomKey = apiKeys[Math.floor(Math.random() * apiKeys.length)];
    const genAI = new GoogleGenerativeAI(randomKey);
    
    // 2. Intelligent System Instruction
    const systemInstruction = `
      You are Senura, the premium AI personal shopping assistant for VibeCart. 
      Your task is to chat with the user naturally and extract gift details to search Kapruka's e-commerce inventory.
      
      CRITICAL INSTRUCTIONS:
      1. Always maintain a warm, helpful, and friendly vibe.
      2. If the user mentions a specific product category (e.g., "cakes", "sarees", "phones"), your "searchQuery" MUST strictly be the single, singular noun of that product (e.g. "cake", "saree", "phone"). Never append generic words like "gift".
      3. If the user uses vague terms like "more", "other options", or "something else", look back at the conversation history, identify what product category you just showed them, and carry that noun forward in the "searchQuery" field.
      4. If the user says "gift something" but hasn't picked a specific item type, look at their answers for recipient, occasion, or vibe, and generate 1-2 strategic keywords (e.g., if vibe is 'techy', use 'smartwatch').
      5. Never show rigid multiple-choice menus. Keep the conversation fluid and human.

      You must return strictly a JSON object with this exact structure:
      {
        "naturalReply": "Your conversational response here.",
        "intent": "browse" | "gift" | "chitchat",
        "searchQuery": "Optimized singular product term, or empty string.",
        "extractedParameters": {
          "relationship": "mother" | "partner" | "friend" | "brother" | "unknown",
          "occasion": "birthday" | "anniversary" | "unknown",
          "budgetMax": 999999
        }
      }
    `;

    // Initialize model with System Instruction properly placed
    const model = genAI.getGenerativeModel({ 
      model: "gemini-2.5-flash",
      systemInstruction: systemInstruction,
      generationConfig: { responseMimeType: "application/json" } 
    });

    // 3. Format history safely (No system instruction here, no empty strings)
    const safeMessage = message ? message : " ";
    
    const formattedContents = [
      ...history.map((m: any) => {
        const contentStr = typeof m.content === "string" ? m.content : JSON.stringify(m.content);
        return {
          role: m.role === "assistant" ? "model" : "user",
          parts: [{ text: contentStr ? contentStr : " " }]
        };
      }),
      { role: "user", parts: [{ text: safeMessage }] }
    ];

    const result = await model.generateContent({ contents: formattedContents });
    const responseText = result.response.text();
    
    // Parse the structured payload generated by the LLM
    const parsedData = JSON.parse(responseText);

    return NextResponse.json(parsedData);

  } catch (error: any) {
    console.error("Orchestrated Chat Error:", error);
    return NextResponse.json({ 
      naturalReply: "An error occurred, but I'm still here! Let's try that again.",
      intent: "chitchat",
      searchQuery: "",
      extractedParameters: { relationship: "unknown", occasion: "unknown", budgetMax: 999999 }
    }, { status: 200 }); // Graceful fallback response
  }
}
